import { createContext, useContext, useState } from "react"

/* export const GlobalContext = createContext() */

const TripsContext = createContext()

const initialTrips = [
  {
    id: 1,
    destination: "Roma",
    startDate: "2026-05-02",
    endDate: "2026-05-06",
    participants: [
      {
        id: 1,
        firstName: "Marco",
        lastName: "Rossi",
        phone: "3331234567",
        email: "marco.rossi@example.com",
        fiscalCode: "RSSMRC90A01H501U",
      },
      {
        id: 2,
        firstName: "Giulia",
        lastName: "Bianchi",
        phone: "3339876543",
        email: "giulia.bianchi@example.com",
        fiscalCode: "BNCGLI92B41F205X",
      },
      {
        id: 3,
        firstName: "Luca",
        lastName: "Verdi",
        phone: "3334567890",
        email: "luca.verdi@example.com",
        fiscalCode: "VRDLCU88C15D612K",
      },
      {
        id: 4,
        firstName: "Martina",
        lastName: "Ferrari",
        phone: "3332223344",
        email: "martina.ferrari@example.com",
        fiscalCode: "FRRMTN94D22F205L",
      },
      {
        id: 5,
        firstName: "Davide",
        lastName: "Romano",
        phone: "3335556677",
        email: "davide.romano@example.com",
        fiscalCode: "RMNDVD90E18H501P",
      },
    ],
  },
  {
    id: 2,
    destination: "Milano",
    startDate: "2026-05-10",
    endDate: "2026-05-14",
    participants: [
      {
        id: 1,
        firstName: "Sara",
        lastName: "Romano",
        phone: "3341112233",
        email: "sara.romano@example.com",
        fiscalCode: "RMNSRA91D45F205Z",
      },
      {
        id: 2,
        firstName: "Davide",
        lastName: "Ferrari",
        phone: "3344445566",
        email: "davide.ferrari@example.com",
        fiscalCode: "FRRDVD89E12L219P",
      },
      {
        id: 3,
        firstName: "Martina",
        lastName: "Greco",
        phone: "3347778899",
        email: "martina.greco@example.com",
        fiscalCode: "GRCMTN94F20A944L",
      },
      {
        id: 4,
        firstName: "Alessio",
        lastName: "Gallo",
        phone: "3342223344",
        email: "alessio.gallo@example.com",
        fiscalCode: "GLLLSS92G10F205T",
      },
      {
        id: 5,
        firstName: "Federica",
        lastName: "Costa",
        phone: "3345556677",
        email: "federica.costa@example.com",
        fiscalCode: "CSTFRC95H41L219M",
      },
      {
        id: 6,
        firstName: "Riccardo",
        lastName: "Moretti",
        phone: "3348889900",
        email: "riccardo.moretti@example.com",
        fiscalCode: "MRTRCR88I15F205N",
      },
    ],
  },
  {
    id: 3,
    destination: "Firenze",
    startDate: "2026-05-15",
    endDate: "2026-05-18",
    participants: [
      {
        id: 1,
        firstName: "Alessandro",
        lastName: "Conti",
        phone: "3351234567",
        email: "alessandro.conti@example.com",
        fiscalCode: "CNTLSN87G10D612R",
      },
      {
        id: 2,
        firstName: "Elena",
        lastName: "Marini",
        phone: "3359876543",
        email: "elena.marini@example.com",
        fiscalCode: "MRNLNE93H22H501S",
      },
      {
        id: 3,
        firstName: "Francesco",
        lastName: "Gallo",
        phone: "3354567890",
        email: "francesco.gallo@example.com",
        fiscalCode: "GLLFNC90I18F839M",
      },
      {
        id: 4,
        firstName: "Chiara",
        lastName: "Ricci",
        phone: "3352223344",
        email: "chiara.ricci@example.com",
        fiscalCode: "RCCCHR94L41D612A",
      },
      {
        id: 5,
        firstName: "Tommaso",
        lastName: "Serra",
        phone: "3355556677",
        email: "tommaso.serra@example.com",
        fiscalCode: "SRRTMS89M10D612B",
      },
      {
        id: 6,
        firstName: "Ilaria",
        lastName: "Lombardi",
        phone: "3358889900",
        email: "ilaria.lombardi@example.com",
        fiscalCode: "LMBLRI96N55D612C",
      },
      {
        id: 7,
        firstName: "Paolo",
        lastName: "Mancini",
        phone: "3353334455",
        email: "paolo.mancini@example.com",
        fiscalCode: "MNCPLA91P15D612D",
      },
    ],
  },
  {
    id: 4,
    destination: "Venezia",
    startDate: "2026-05-20",
    endDate: "2026-05-24",
    participants: [
      {
        id: 1,
        firstName: "Chiara",
        lastName: "Moretti",
        phone: "3361112233",
        email: "chiara.moretti@example.com",
        fiscalCode: "MRTCHR95L44L736Q",
      },
      {
        id: 2,
        firstName: "Matteo",
        lastName: "Ricci",
        phone: "3364445566",
        email: "matteo.ricci@example.com",
        fiscalCode: "RCCMTT88M12H501P",
      },
      {
        id: 3,
        firstName: "Laura",
        lastName: "Esposito",
        phone: "3367778899",
        email: "laura.esposito@example.com",
        fiscalCode: "SPSLRA93N55F839T",
      },
      {
        id: 4,
        firstName: "Giorgia",
        lastName: "Rinaldi",
        phone: "3362223344",
        email: "giorgia.rinaldi@example.com",
        fiscalCode: "RNLGRA97A41L736E",
      },
      {
        id: 5,
        firstName: "Simone",
        lastName: "Fontana",
        phone: "3365556677",
        email: "simone.fontana@example.com",
        fiscalCode: "FNTSMN90B10L736F",
      },
      {
        id: 6,
        firstName: "Valentina",
        lastName: "Barbieri",
        phone: "3368889900",
        email: "valentina.barbieri@example.com",
        fiscalCode: "BRBVNT92C55L736G",
      },
      {
        id: 7,
        firstName: "Roberto",
        lastName: "Leone",
        phone: "3363334455",
        email: "roberto.leone@example.com",
        fiscalCode: "LNERBT89D15L736H",
      },
      {
        id: 8,
        firstName: "Silvia",
        lastName: "Fabbri",
        phone: "3366667788",
        email: "silvia.fabbri@example.com",
        fiscalCode: "FBBSLV94E41L736I",
      },
    ],
  },
  {
    id: 5,
    destination: "Napoli",
    startDate: "2026-05-25",
    endDate: "2026-05-30",
    participants: [
      {
        id: 1,
        firstName: "Antonio",
        lastName: "Russo",
        phone: "3371234567",
        email: "antonio.russo@example.com",
        fiscalCode: "RSSNTN89P10F839Y",
      },
      {
        id: 2,
        firstName: "Federica",
        lastName: "De Luca",
        phone: "3379876543",
        email: "federica.deluca@example.com",
        fiscalCode: "DLCFRC94R41F839A",
      },
      {
        id: 3,
        firstName: "Gennaro",
        lastName: "Coppola",
        phone: "3374567890",
        email: "gennaro.coppola@example.com",
        fiscalCode: "CPPGNR90S15F839B",
      },
      {
        id: 4,
        firstName: "Roberta",
        lastName: "Amato",
        phone: "3372223344",
        email: "roberta.amato@example.com",
        fiscalCode: "MTARBT92H15F839C",
      },
      {
        id: 5,
        firstName: "Salvatore",
        lastName: "Vitale",
        phone: "3375556677",
        email: "salvatore.vitale@example.com",
        fiscalCode: "VTLSVT88I10F839D",
      },
      {
        id: 6,
        firstName: "Claudia",
        lastName: "Messina",
        phone: "3378889900",
        email: "claudia.messina@example.com",
        fiscalCode: "MSSCLD95L41F839E",
      },
      {
        id: 7,
        firstName: "Nicola",
        lastName: "Marino",
        phone: "3373334455",
        email: "nicola.marino@example.com",
        fiscalCode: "MRNNCL90M15F839F",
      },
      {
        id: 8,
        firstName: "Arianna",
        lastName: "Greco",
        phone: "3376667788",
        email: "arianna.greco@example.com",
        fiscalCode: "GRCRNN96N41F839G",
      },
      {
        id: 9,
        firstName: "Fabio",
        lastName: "Caruso",
        phone: "3379990011",
        email: "fabio.caruso@example.com",
        fiscalCode: "CRSFBA91P10F839H",
      },
    ],
  },
  {
    id: 6,
    destination: "Torino",
    startDate: "2026-06-01",
    endDate: "2026-06-05",
    participants: [
      {
        id: 1,
        firstName: "Simone",
        lastName: "Barbieri",
        phone: "3381112233",
        email: "simone.barbieri@example.com",
        fiscalCode: "BRBSMN91T22L219C",
      },
      {
        id: 2,
        firstName: "Valentina",
        lastName: "Riva",
        phone: "3384445566",
        email: "valentina.riva@example.com",
        fiscalCode: "RVAVNT92A45L219D",
      },
      {
        id: 3,
        firstName: "Andrea",
        lastName: "Fontana",
        phone: "3387778899",
        email: "andrea.fontana@example.com",
        fiscalCode: "FNTNDR88B18L219E",
      },
      {
        id: 4,
        firstName: "Beatrice",
        lastName: "Lupo",
        phone: "3382223344",
        email: "beatrice.lupo@example.com",
        fiscalCode: "LPUBRC96C41L219F",
      },
      {
        id: 5,
        firstName: "Edoardo",
        lastName: "Sala",
        phone: "3385556677",
        email: "edoardo.sala@example.com",
        fiscalCode: "SLADRD89D10L219G",
      },
      {
        id: 6,
        firstName: "Noemi",
        lastName: "Pellegrini",
        phone: "3388889900",
        email: "noemi.pellegrini@example.com",
        fiscalCode: "PLLNOE94E55L219H",
      },
      {
        id: 7,
        firstName: "Daniele",
        lastName: "Grassi",
        phone: "3383334455",
        email: "daniele.grassi@example.com",
        fiscalCode: "GRSDNL90F15L219I",
      },
      {
        id: 8,
        firstName: "Greta",
        lastName: "Martini",
        phone: "3386667788",
        email: "greta.martini@example.com",
        fiscalCode: "MRTGRT97G41L219J",
      },
      {
        id: 9,
        firstName: "Manuel",
        lastName: "Piras",
        phone: "3389990011",
        email: "manuel.piras@example.com",
        fiscalCode: "PRSMNL88H10L219K",
      },
      {
        id: 10,
        firstName: "Viola",
        lastName: "Sanna",
        phone: "3381239988",
        email: "viola.sanna@example.com",
        fiscalCode: "SNNVLI95I41L219L",
      },
    ],
  },
  {
    id: 7,
    destination: "Bologna",
    startDate: "2026-06-07",
    endDate: "2026-06-10",
    participants: [
      {
        id: 1,
        firstName: "Roberto",
        lastName: "Fabbri",
        phone: "3391234567",
        email: "roberto.fabbri@example.com",
        fiscalCode: "FBBRRT87C10A944F",
      },
      {
        id: 2,
        firstName: "Silvia",
        lastName: "Costa",
        phone: "3399876543",
        email: "silvia.costa@example.com",
        fiscalCode: "CSTSLV93D41A944G",
      },
      {
        id: 3,
        firstName: "Michele",
        lastName: "Leone",
        phone: "3394567890",
        email: "michele.leone@example.com",
        fiscalCode: "LNEMHL90E15A944H",
      },
      {
        id: 4,
        firstName: "Cristina",
        lastName: "Basile",
        phone: "3392223344",
        email: "cristina.basile@example.com",
        fiscalCode: "BSLCRS96L41A944M",
      },
      {
        id: 5,
        firstName: "Lorenzo",
        lastName: "Villa",
        phone: "3395556677",
        email: "lorenzo.villa@example.com",
        fiscalCode: "VLLLNZ89M10A944N",
      },
      {
        id: 6,
        firstName: "Marta",
        lastName: "Rizzo",
        phone: "3398889900",
        email: "marta.rizzo@example.com",
        fiscalCode: "RZZMRT94N55A944P",
      },
      {
        id: 7,
        firstName: "Pietro",
        lastName: "Guerra",
        phone: "3393334455",
        email: "pietro.guerra@example.com",
        fiscalCode: "GRRPTR91P15A944Q",
      },
      {
        id: 8,
        firstName: "Camilla",
        lastName: "Longo",
        phone: "3396667788",
        email: "camilla.longo@example.com",
        fiscalCode: "LNGCLL95R41A944R",
      },
      {
        id: 9,
        firstName: "Samuele",
        lastName: "Parisi",
        phone: "3399990011",
        email: "samuele.parisi@example.com",
        fiscalCode: "PRSSML90S10A944S",
      },
      {
        id: 10,
        firstName: "Alice",
        lastName: "Gentile",
        phone: "3391239988",
        email: "alice.gentile@example.com",
        fiscalCode: "GNTLCA96T41A944T",
      },
      {
        id: 11,
        firstName: "Diego",
        lastName: "Palmieri",
        phone: "3397776655",
        email: "diego.palmieri@example.com",
        fiscalCode: "PLMDGI88A15A944U",
      },
    ],
  },
  {
    id: 8,
    destination: "Palermo",
    startDate: "2026-06-12",
    endDate: "2026-06-17",
    participants: [
      {
        id: 1,
        firstName: "Salvatore",
        lastName: "Messina",
        phone: "3401112233",
        email: "salvatore.messina@example.com",
        fiscalCode: "MSSSVT89F10G273J",
      },
      {
        id: 2,
        firstName: "Claudia",
        lastName: "Vitale",
        phone: "3404445566",
        email: "claudia.vitale@example.com",
        fiscalCode: "VTLCLD94G41G273K",
      },
      {
        id: 3,
        firstName: "Roberta",
        lastName: "Amato",
        phone: "3407778899",
        email: "roberta.amato@example.com",
        fiscalCode: "MTARBT92H15G273L",
      },
      {
        id: 4,
        firstName: "Enrico",
        lastName: "Lombardo",
        phone: "3402223344",
        email: "enrico.lombardo@example.com",
        fiscalCode: "LMBNRC87I10G273A",
      },
      {
        id: 5,
        firstName: "Serena",
        lastName: "Ferraro",
        phone: "3405556677",
        email: "serena.ferraro@example.com",
        fiscalCode: "FRRSRN95L41G273B",
      },
      {
        id: 6,
        firstName: "Gabriele",
        lastName: "Marchetti",
        phone: "3408889900",
        email: "gabriele.marchetti@example.com",
        fiscalCode: "MRCGBR90M15G273C",
      },
      {
        id: 7,
        firstName: "Rachele",
        lastName: "D'Amico",
        phone: "3403334455",
        email: "rachele.damico@example.com",
        fiscalCode: "DMCRHL96N41G273D",
      },
      {
        id: 8,
        firstName: "Ivan",
        lastName: "Pagano",
        phone: "3406667788",
        email: "ivan.pagano@example.com",
        fiscalCode: "PGNIVN88P10G273E",
      },
      {
        id: 9,
        firstName: "Aurora",
        lastName: "Santoro",
        phone: "3409990011",
        email: "aurora.santoro@example.com",
        fiscalCode: "SNTRRA97R41G273F",
      },
      {
        id: 10,
        firstName: "Mattia",
        lastName: "Farina",
        phone: "3401239988",
        email: "mattia.farina@example.com",
        fiscalCode: "FRNMTT91S15G273G",
      },
      {
        id: 11,
        firstName: "Ludovica",
        lastName: "De Santis",
        phone: "3407776655",
        email: "ludovica.desantis@example.com",
        fiscalCode: "DSNLVC95T41G273H",
      },
      {
        id: 12,
        firstName: "Kevin",
        lastName: "Orlando",
        phone: "3405554433",
        email: "kevin.orlando@example.com",
        fiscalCode: "RLNKVN89A10G273I",
      },
    ],
  },
  {
    id: 9,
    destination: "Bari",
    startDate: "2026-06-20",
    endDate: "2026-06-23",
    participants: [
      {
        id: 1,
        firstName: "Nicola",
        lastName: "Lombardi",
        phone: "3411234567",
        email: "nicola.lombardi@example.com",
        fiscalCode: "LMBNCL88I10A662M",
      },
      {
        id: 2,
        firstName: "Ilaria",
        lastName: "Serra",
        phone: "3419876543",
        email: "ilaria.serra@example.com",
        fiscalCode: "SRRLRI95L41A662N",
      },
      {
        id: 3,
        firstName: "Paolo",
        lastName: "Mancini",
        phone: "3414567890",
        email: "paolo.mancini@example.com",
        fiscalCode: "MNCPLA90M15A662P",
      },
      {
        id: 4,
        firstName: "Nadia",
        lastName: "Bruno",
        phone: "3412223344",
        email: "nadia.bruno@example.com",
        fiscalCode: "BRNNDA94N41A662Q",
      },
      {
        id: 5,
        firstName: "Stefano",
        lastName: "Fiore",
        phone: "3415556677",
        email: "stefano.fiore@example.com",
        fiscalCode: "FRISFN87P10A662R",
      },
      {
        id: 6,
        firstName: "Monica",
        lastName: "Pellegrino",
        phone: "3418889900",
        email: "monica.pellegrino@example.com",
        fiscalCode: "PLLMNC96R41A662S",
      },
      {
        id: 7,
        firstName: "Vincenzo",
        lastName: "Martino",
        phone: "3413334455",
        email: "vincenzo.martino@example.com",
        fiscalCode: "MRTVCN90S15A662T",
      },
      {
        id: 8,
        firstName: "Eleonora",
        lastName: "Carbone",
        phone: "3416667788",
        email: "eleonora.carbone@example.com",
        fiscalCode: "CRBLNR95T41A662U",
      },
      {
        id: 9,
        firstName: "Cristian",
        lastName: "Esposito",
        phone: "3419990011",
        email: "cristian.esposito@example.com",
        fiscalCode: "SPSCRS89A10A662V",
      },
      {
        id: 10,
        firstName: "Sofia",
        lastName: "Caputo",
        phone: "3411239988",
        email: "sofia.caputo@example.com",
        fiscalCode: "CPTSFO97B41A662W",
      },
      {
        id: 11,
        firstName: "Emanuele",
        lastName: "Ruggiero",
        phone: "3417776655",
        email: "emanuele.ruggiero@example.com",
        fiscalCode: "RGGMNL88C15A662X",
      },
      {
        id: 12,
        firstName: "Veronica",
        lastName: "De Rosa",
        phone: "3415554433",
        email: "veronica.derosa@example.com",
        fiscalCode: "DRS VNC96D41A662Y".replace(" ", ""),
      },
      {
        id: 13,
        firstName: "Alberto",
        lastName: "Sorrentino",
        phone: "3414443322",
        email: "alberto.sorrentino@example.com",
        fiscalCode: "SRRLRT90E10A662Z",
      },
    ],
  },
  {
    id: 10,
    destination: "Cagliari",
    startDate: "2026-06-25",
    endDate: "2026-06-29",
    participants: [
      {
        id: 1,
        firstName: "Giorgio",
        lastName: "Sanna",
        phone: "3421112233",
        email: "giorgio.sanna@example.com",
        fiscalCode: "SNNGRG87N10B354Q",
      },
      {
        id: 2,
        firstName: "Arianna",
        lastName: "Piras",
        phone: "3424445566",
        email: "arianna.piras@example.com",
        fiscalCode: "PRSRNN94P41B354R",
      },
      {
        id: 3,
        firstName: "Fabio",
        lastName: "Melis",
        phone: "3427778899",
        email: "fabio.melis@example.com",
        fiscalCode: "MLSFBA91R15B354S",
      },
      {
        id: 4,
        firstName: "Miriam",
        lastName: "Carta",
        phone: "3422223344",
        email: "miriam.carta@example.com",
        fiscalCode: "CRTMRM96T41B354A",
      },
      {
        id: 5,
        firstName: "Leonardo",
        lastName: "Fois",
        phone: "3425556677",
        email: "leonardo.fois@example.com",
        fiscalCode: "FSOLRD89A10B354B",
      },
      {
        id: 6,
        firstName: "Rebecca",
        lastName: "Manca",
        phone: "3428889900",
        email: "rebecca.manca@example.com",
        fiscalCode: "MNCRCC95B41B354C",
      },
      {
        id: 7,
        firstName: "Dario",
        lastName: "Serra",
        phone: "3423334455",
        email: "dario.serra@example.com",
        fiscalCode: "SRRDRA90C15B354D",
      },
      {
        id: 8,
        firstName: "Flavia",
        lastName: "Lai",
        phone: "3426667788",
        email: "flavia.lai@example.com",
        fiscalCode: "LAIFLV97D41B354E",
      },
      {
        id: 9,
        firstName: "Claudio",
        lastName: "Usai",
        phone: "3429990011",
        email: "claudio.usai@example.com",
        fiscalCode: "SUACLD88E10B354F",
      },
      {
        id: 10,
        firstName: "Teresa",
        lastName: "Murgia",
        phone: "3421239988",
        email: "teresa.murgia@example.com",
        fiscalCode: "MRGTRS96F41B354G",
      },
      {
        id: 11,
        firstName: "Samira",
        lastName: "Cossu",
        phone: "3427776655",
        email: "samira.cossu@example.com",
        fiscalCode: "CSSSMR94G41B354H",
      },
      {
        id: 12,
        firstName: "Filippo",
        lastName: "Pinna",
        phone: "3425554433",
        email: "filippo.pinna@example.com",
        fiscalCode: "PNNFPP89H10B354I",
      },
      {
        id: 13,
        firstName: "Cecilia",
        lastName: "Nieddu",
        phone: "3424443322",
        email: "cecilia.nieddu@example.com",
        fiscalCode: "NDDCCL95I41B354J",
      },
      {
        id: 14,
        firstName: "Loris",
        lastName: "Sechi",
        phone: "3423332211",
        email: "loris.sechi@example.com",
        fiscalCode: "SCHLRS90L15B354K",
      },
    ],
  },
  {
    id: 11,
    destination: "Parigi",
    startDate: "2026-07-02",
    endDate: "2026-07-07",
    participants: [
      {
        id: 1,
        firstName: "Emma",
        lastName: "Bernard",
        phone: "3431112233",
        email: "emma.bernard@example.com",
        fiscalCode: "BRNMME95A41Z110A",
      },
      {
        id: 2,
        firstName: "Julien",
        lastName: "Moreau",
        phone: "3434445566",
        email: "julien.moreau@example.com",
        fiscalCode: "MROJLN90B10Z110B",
      },
      {
        id: 3,
        firstName: "Camille",
        lastName: "Leroy",
        phone: "3437778899",
        email: "camille.leroy@example.com",
        fiscalCode: "LRYCML97C41Z110C",
      },
      {
        id: 4,
        firstName: "Hugo",
        lastName: "Petit",
        phone: "3432223344",
        email: "hugo.petit@example.com",
        fiscalCode: "PTTHGU89D10Z110D",
      },
      {
        id: 5,
        firstName: "Chloe",
        lastName: "Dubois",
        phone: "3435556677",
        email: "chloe.dubois@example.com",
        fiscalCode: "DBSCHL96E41Z110E",
      },
      {
        id: 6,
        firstName: "Louis",
        lastName: "Martin",
        phone: "3438889900",
        email: "louis.martin@example.com",
        fiscalCode: "MRTLSU91F15Z110F",
      },
      {
        id: 7,
        firstName: "Ines",
        lastName: "Roux",
        phone: "3433334455",
        email: "ines.roux@example.com",
        fiscalCode: "ROXNSI95G41Z110G",
      },
      {
        id: 8,
        firstName: "Noah",
        lastName: "Garcia",
        phone: "3436667788",
        email: "noah.garcia@example.com",
        fiscalCode: "GRCNHO90H10Z110H",
      },
      {
        id: 9,
        firstName: "Alice",
        lastName: "Fournier",
        phone: "3439990011",
        email: "alice.fournier@example.com",
        fiscalCode: "FRNLCA98I41Z110I",
      },
      {
        id: 10,
        firstName: "Leo",
        lastName: "Girard",
        phone: "3431239988",
        email: "leo.girard@example.com",
        fiscalCode: "GRDLEO88L10Z110J",
      },
      {
        id: 11,
        firstName: "Manon",
        lastName: "Lambert",
        phone: "3437776655",
        email: "manon.lambert@example.com",
        fiscalCode: "LMBMNN94M41Z110K",
      },
      {
        id: 12,
        firstName: "Arthur",
        lastName: "Blanc",
        phone: "3435554433",
        email: "arthur.blanc@example.com",
        fiscalCode: "BLNRHR89N10Z110L",
      },
      {
        id: 13,
        firstName: "Lina",
        lastName: "Faure",
        phone: "3434443322",
        email: "lina.faure@example.com",
        fiscalCode: "FRALNI97P41Z110M",
      },
      {
        id: 14,
        firstName: "Ethan",
        lastName: "Andre",
        phone: "3433332211",
        email: "ethan.andre@example.com",
        fiscalCode: "NDRTHN90R10Z110N",
      },
      {
        id: 15,
        firstName: "Sarah",
        lastName: "Mercier",
        phone: "3432221100",
        email: "sarah.mercier@example.com",
        fiscalCode: "MRCSRH96S41Z110P",
      },
    ],
  },
  {
    id: 12,
    destination: "Londra",
    startDate: "2026-07-10",
    endDate: "2026-07-15",
    participants: [
      {
        id: 1,
        firstName: "Oliver",
        lastName: "Smith",
        phone: "3441112233",
        email: "oliver.smith@example.com",
        fiscalCode: "SMTLVR90A10Z114A",
      },
      {
        id: 2,
        firstName: "Amelia",
        lastName: "Johnson",
        phone: "3444445566",
        email: "amelia.johnson@example.com",
        fiscalCode: "JHNM LA96B41Z114B".replace(" ", ""),
      },
      {
        id: 3,
        firstName: "George",
        lastName: "Williams",
        phone: "3447778899",
        email: "george.williams@example.com",
        fiscalCode: "WLLGRG89C10Z114C",
      },
      {
        id: 4,
        firstName: "Isla",
        lastName: "Brown",
        phone: "3442223344",
        email: "isla.brown@example.com",
        fiscalCode: "BRNSLI97D41Z114D",
      },
      {
        id: 5,
        firstName: "Harry",
        lastName: "Taylor",
        phone: "3445556677",
        email: "harry.taylor@example.com",
        fiscalCode: "TYLHRR91E15Z114E",
      },
      {
        id: 6,
        firstName: "Sophia",
        lastName: "Davies",
        phone: "3448889900",
        email: "sophia.davies@example.com",
        fiscalCode: "DVSSPH95F41Z114F",
      },
      {
        id: 7,
        firstName: "Jack",
        lastName: "Evans",
        phone: "3443334455",
        email: "jack.evans@example.com",
        fiscalCode: "VNSJCK90G10Z114G",
      },
      {
        id: 8,
        firstName: "Grace",
        lastName: "Wilson",
        phone: "3446667788",
        email: "grace.wilson@example.com",
        fiscalCode: "WLSGRC98H41Z114H",
      },
      {
        id: 9,
        firstName: "Charlie",
        lastName: "Thomas",
        phone: "3449990011",
        email: "charlie.thomas@example.com",
        fiscalCode: "THMCRL88I10Z114I",
      },
      {
        id: 10,
        firstName: "Emily",
        lastName: "Roberts",
        phone: "3441239988",
        email: "emily.roberts@example.com",
        fiscalCode: "RBREML96L41Z114J",
      },
    ],
  },
  {
    id: 13,
    destination: "Barcellona",
    startDate: "2026-07-18",
    endDate: "2026-07-22",
    participants: [
      {
        id: 1,
        firstName: "Carlos",
        lastName: "Garcia",
        phone: "3451112233",
        email: "carlos.garcia@example.com",
        fiscalCode: "GRCCLS90A10Z131A",
      },
      {
        id: 2,
        firstName: "Lucia",
        lastName: "Martinez",
        phone: "3454445566",
        email: "lucia.martinez@example.com",
        fiscalCode: "MRTL CU96B41Z131B".replace(" ", ""),
      },
      {
        id: 3,
        firstName: "Pablo",
        lastName: "Lopez",
        phone: "3457778899",
        email: "pablo.lopez@example.com",
        fiscalCode: "LPZPBL89C10Z131C",
      },
      {
        id: 4,
        firstName: "Marta",
        lastName: "Sanchez",
        phone: "3452223344",
        email: "marta.sanchez@example.com",
        fiscalCode: "SNCMRT95D41Z131D",
      },
      {
        id: 5,
        firstName: "Diego",
        lastName: "Romero",
        phone: "3455556677",
        email: "diego.romero@example.com",
        fiscalCode: "RMRDGI91E15Z131E",
      },
      {
        id: 6,
        firstName: "Sofia",
        lastName: "Torres",
        phone: "3458889900",
        email: "sofia.torres@example.com",
        fiscalCode: "TRRSFO97F41Z131F",
      },
      {
        id: 7,
        firstName: "Adrian",
        lastName: "Navarro",
        phone: "3453334455",
        email: "adrian.navarro@example.com",
        fiscalCode: "NVRDRN90G10Z131G",
      },
      {
        id: 8,
        firstName: "Elena",
        lastName: "Ruiz",
        phone: "3456667788",
        email: "elena.ruiz@example.com",
        fiscalCode: "RUZLNE96H41Z131H",
      },
    ],
  },
  {
    id: 14,
    destination: "Amsterdam",
    startDate: "2026-07-25",
    endDate: "2026-07-30",
    participants: [
      {
        id: 1,
        firstName: "Daan",
        lastName: "De Vries",
        phone: "3461112233",
        email: "daan.devries@example.com",
        fiscalCode: "DVRDNA90A10Z126A",
      },
      {
        id: 2,
        firstName: "Sanne",
        lastName: "Jansen",
        phone: "3464445566",
        email: "sanne.jansen@example.com",
        fiscalCode: "JNSSNN96B41Z126B",
      },
      {
        id: 3,
        firstName: "Luuk",
        lastName: "Bakker",
        phone: "3467778899",
        email: "luuk.bakker@example.com",
        fiscalCode: "BKKLKU89C10Z126C",
      },
      {
        id: 4,
        firstName: "Emma",
        lastName: "Visser",
        phone: "3462223344",
        email: "emma.visser@example.com",
        fiscalCode: "VSSMME95D41Z126D",
      },
      {
        id: 5,
        firstName: "Milan",
        lastName: "Smit",
        phone: "3465556677",
        email: "milan.smit@example.com",
        fiscalCode: "SMTMLN91E15Z126E",
      },
      {
        id: 6,
        firstName: "Noor",
        lastName: "Meijer",
        phone: "3468889900",
        email: "noor.meijer@example.com",
        fiscalCode: "MJRNRO97F41Z126F",
      },
      {
        id: 7,
        firstName: "Finn",
        lastName: "Mulder",
        phone: "3463334455",
        email: "finn.mulder@example.com",
        fiscalCode: "MLDFNN90G10Z126G",
      },
      {
        id: 8,
        firstName: "Lotte",
        lastName: "Bos",
        phone: "3466667788",
        email: "lotte.bos@example.com",
        fiscalCode: "BOSLTT96H41Z126H",
      },
      {
        id: 9,
        firstName: "Jesse",
        lastName: "Vos",
        phone: "3469990011",
        email: "jesse.vos@example.com",
        fiscalCode: "VOSJSS88I10Z126I",
      },
    ],
  },
  {
    id: 15,
    destination: "Berlino",
    startDate: "2026-08-03",
    endDate: "2026-08-08",
    participants: [
      {
        id: 1,
        firstName: "Lukas",
        lastName: "Muller",
        phone: "3471112233",
        email: "lukas.muller@example.com",
        fiscalCode: "MLLLKS90A10Z112A",
      },
      {
        id: 2,
        firstName: "Anna",
        lastName: "Schmidt",
        phone: "3474445566",
        email: "anna.schmidt@example.com",
        fiscalCode: "SCHNNA96B41Z112B",
      },
      {
        id: 3,
        firstName: "Felix",
        lastName: "Weber",
        phone: "3477778899",
        email: "felix.weber@example.com",
        fiscalCode: "WBRFLX89C10Z112C",
      },
      {
        id: 4,
        firstName: "Mia",
        lastName: "Fischer",
        phone: "3472223344",
        email: "mia.fischer@example.com",
        fiscalCode: "FSCMIA95D41Z112D",
      },
      {
        id: 5,
        firstName: "Leon",
        lastName: "Wagner",
        phone: "3475556677",
        email: "leon.wagner@example.com",
        fiscalCode: "WGNLEO91E15Z112E",
      },
      {
        id: 6,
        firstName: "Laura",
        lastName: "Becker",
        phone: "3478889900",
        email: "laura.becker@example.com",
        fiscalCode: "BCKLRA97F41Z112F",
      },
      {
        id: 7,
        firstName: "Jonas",
        lastName: "Hoffmann",
        phone: "3473334455",
        email: "jonas.hoffmann@example.com",
        fiscalCode: "HFFJNS90G10Z112G",
      },
      {
        id: 8,
        firstName: "Lea",
        lastName: "Schneider",
        phone: "3476667788",
        email: "lea.schneider@example.com",
        fiscalCode: "SCHLEA96H41Z112H",
      },
      {
        id: 9,
        firstName: "Tim",
        lastName: "Koch",
        phone: "3479990011",
        email: "tim.koch@example.com",
        fiscalCode: "KCHTMI88I10Z112I",
      },
      {
        id: 10,
        firstName: "Nina",
        lastName: "Bauer",
        phone: "3471239988",
        email: "nina.bauer@example.com",
        fiscalCode: "BAUNNI96L41Z112J",
      },
      {
        id: 11,
        firstName: "Erik",
        lastName: "Richter",
        phone: "3477776655",
        email: "erik.richter@example.com",
        fiscalCode: "RCHERK89M10Z112K",
      },
    ],
  },
  {
    id: 16,
    destination: "Praga",
    startDate: "2026-08-11",
    endDate: "2026-08-15",
    participants: [
      {
        id: 1,
        firstName: "Tomas",
        lastName: "Novak",
        phone: "3481112233",
        email: "tomas.novak@example.com",
        fiscalCode: "NVKTMS90A10Z156A",
      },
      {
        id: 2,
        firstName: "Eva",
        lastName: "Svoboda",
        phone: "3484445566",
        email: "eva.svoboda@example.com",
        fiscalCode: "SVBVAE96B41Z156B",
      },
      {
        id: 3,
        firstName: "Jan",
        lastName: "Dvorak",
        phone: "3487778899",
        email: "jan.dvorak@example.com",
        fiscalCode: "DVRJNA89C10Z156C",
      },
      {
        id: 4,
        firstName: "Petra",
        lastName: "Prochazka",
        phone: "3482223344",
        email: "petra.prochazka@example.com",
        fiscalCode: "PRCPTR95D41Z156D",
      },
      {
        id: 5,
        firstName: "Martin",
        lastName: "Kucera",
        phone: "3485556677",
        email: "martin.kucera@example.com",
        fiscalCode: "KCRMRT91E15Z156E",
      },
      {
        id: 6,
        firstName: "Lucie",
        lastName: "Vesela",
        phone: "3488889900",
        email: "lucie.vesela@example.com",
        fiscalCode: "VSLLCU97F41Z156F",
      },
      {
        id: 7,
        firstName: "Adam",
        lastName: "Horak",
        phone: "3483334455",
        email: "adam.horak@example.com",
        fiscalCode: "HRKDMA90G10Z156G",
      },
    ],
  },
  {
    id: 17,
    destination: "Vienna",
    startDate: "2026-08-18",
    endDate: "2026-08-22",
    participants: [
      {
        id: 1,
        firstName: "Maximilian",
        lastName: "Gruber",
        phone: "3491112233",
        email: "maximilian.gruber@example.com",
        fiscalCode: "GRBMXM90A10Z102A",
      },
      {
        id: 2,
        firstName: "Lena",
        lastName: "Huber",
        phone: "3494445566",
        email: "lena.huber@example.com",
        fiscalCode: "HBRLNE96B41Z102B",
      },
      {
        id: 3,
        firstName: "Paul",
        lastName: "Winkler",
        phone: "3497778899",
        email: "paul.winkler@example.com",
        fiscalCode: "WNKPLA89C10Z102C",
      },
      {
        id: 4,
        firstName: "Marlene",
        lastName: "Berger",
        phone: "3492223344",
        email: "marlene.berger@example.com",
        fiscalCode: "BRGMRL95D41Z102D",
      },
      {
        id: 5,
        firstName: "Jakob",
        lastName: "Steiner",
        phone: "3495556677",
        email: "jakob.steiner@example.com",
        fiscalCode: "STNJKB91E15Z102E",
      },
      {
        id: 6,
        firstName: "Hannah",
        lastName: "Moser",
        phone: "3498889900",
        email: "hannah.moser@example.com",
        fiscalCode: "MSRHNN97F41Z102F",
      },
      {
        id: 7,
        firstName: "David",
        lastName: "Bauer",
        phone: "3493334455",
        email: "david.bauer@example.com",
        fiscalCode: "BAUDVD90G10Z102G",
      },
      {
        id: 8,
        firstName: "Sophie",
        lastName: "Fuchs",
        phone: "3496667788",
        email: "sophie.fuchs@example.com",
        fiscalCode: "FCHSPH96H41Z102H",
      },
      {
        id: 9,
        firstName: "Moritz",
        lastName: "Schwarz",
        phone: "3499990011",
        email: "moritz.schwarz@example.com",
        fiscalCode: "SCHMRT88I10Z102I",
      },
      {
        id: 10,
        firstName: "Marie",
        lastName: "Hofer",
        phone: "3491239988",
        email: "marie.hofer@example.com",
        fiscalCode: "HFRMRA96L41Z102J",
      },
      {
        id: 11,
        firstName: "Florian",
        lastName: "Lang",
        phone: "3497776655",
        email: "florian.lang@example.com",
        fiscalCode: "LNGFLR89M10Z102K",
      },
      {
        id: 12,
        firstName: "Nora",
        lastName: "Wolf",
        phone: "3495554433",
        email: "nora.wolf@example.com",
        fiscalCode: "WLFNRO95N41Z102L",
      },
    ],
  },
  {
    id: 18,
    destination: "Atene",
    startDate: "2026-08-25",
    endDate: "2026-08-31",
    participants: [
      {
        id: 1,
        firstName: "Nikos",
        lastName: "Papadopoulos",
        phone: "3501112233",
        email: "nikos.papadopoulos@example.com",
        fiscalCode: "PPDNKS90A10Z115A",
      },
      {
        id: 2,
        firstName: "Eleni",
        lastName: "Georgiou",
        phone: "3504445566",
        email: "eleni.georgiou@example.com",
        fiscalCode: "GRGLNE96B41Z115B",
      },
      {
        id: 3,
        firstName: "Dimitris",
        lastName: "Nikolaou",
        phone: "3507778899",
        email: "dimitris.nikolaou@example.com",
        fiscalCode: "NKLDMT89C10Z115C",
      },
      {
        id: 4,
        firstName: "Maria",
        lastName: "Kostopoulos",
        phone: "3502223344",
        email: "maria.kostopoulos@example.com",
        fiscalCode: "KSTMRA95D41Z115D",
      },
      {
        id: 5,
        firstName: "Alexandros",
        lastName: "Pappas",
        phone: "3505556677",
        email: "alexandros.pappas@example.com",
        fiscalCode: "PPPLSN91E15Z115E",
      },
      {
        id: 6,
        firstName: "Sofia",
        lastName: "Vasileiou",
        phone: "3508889900",
        email: "sofia.vasileiou@example.com",
        fiscalCode: "VSLSFO97F41Z115F",
      },
      {
        id: 7,
        firstName: "Petros",
        lastName: "Dimitriou",
        phone: "3503334455",
        email: "petros.dimitriou@example.com",
        fiscalCode: "DMTPTR90G10Z115G",
      },
      {
        id: 8,
        firstName: "Anna",
        lastName: "Christou",
        phone: "3506667788",
        email: "anna.christou@example.com",
        fiscalCode: "CHRNNA96H41Z115H",
      },
      {
        id: 9,
        firstName: "Giorgos",
        lastName: "Ioannou",
        phone: "3509990011",
        email: "giorgos.ioannou@example.com",
        fiscalCode: "NNIGRG88I10Z115I",
      },
    ],
  },
  {
    id: 19,
    destination: "Lisboa",
    startDate: "2026-09-04",
    endDate: "2026-09-09",
    participants: [
      {
        id: 1,
        firstName: "Joao",
        lastName: "Silva",
        phone: "3511112233",
        email: "joao.silva@example.com",
        fiscalCode: "SLVJOA90A10Z128A",
      },
      {
        id: 2,
        firstName: "Beatriz",
        lastName: "Santos",
        phone: "3514445566",
        email: "beatriz.santos@example.com",
        fiscalCode: "SNTBTR96B41Z128B",
      },
      {
        id: 3,
        firstName: "Miguel",
        lastName: "Ferreira",
        phone: "3517778899",
        email: "miguel.ferreira@example.com",
        fiscalCode: "FRR MGL89C10Z128C".replace(" ", ""),
      },
      {
        id: 4,
        firstName: "Ines",
        lastName: "Costa",
        phone: "3512223344",
        email: "ines.costa@example.com",
        fiscalCode: "CSTNSI95D41Z128D",
      },
      {
        id: 5,
        firstName: "Tiago",
        lastName: "Oliveira",
        phone: "3515556677",
        email: "tiago.oliveira@example.com",
        fiscalCode: "LVRTGI91E15Z128E",
      },
      {
        id: 6,
        firstName: "Matilde",
        lastName: "Pereira",
        phone: "3518889900",
        email: "matilde.pereira@example.com",
        fiscalCode: "PRRMTL97F41Z128F",
      },
      {
        id: 7,
        firstName: "Rafael",
        lastName: "Rodrigues",
        phone: "3513334455",
        email: "rafael.rodrigues@example.com",
        fiscalCode: "RDRRFL90G10Z128G",
      },
      {
        id: 8,
        firstName: "Leonor",
        lastName: "Martins",
        phone: "3516667788",
        email: "leonor.martins@example.com",
        fiscalCode: "MRTLNR96H41Z128H",
      },
      {
        id: 9,
        firstName: "Duarte",
        lastName: "Almeida",
        phone: "3519990011",
        email: "duarte.almeida@example.com",
        fiscalCode: "LMDDRT88I10Z128I",
      },
      {
        id: 10,
        firstName: "Carolina",
        lastName: "Ribeiro",
        phone: "3511239988",
        email: "carolina.ribeiro@example.com",
        fiscalCode: "RBRCRL96L41Z128J",
      },
    ],
  },
  {
    id: 20,
    destination: "Dublino",
    startDate: "2026-09-12",
    endDate: "2026-09-17",
    participants: [
      {
        id: 1,
        firstName: "Sean",
        lastName: "Murphy",
        phone: "3521112233",
        email: "sean.murphy@example.com",
        fiscalCode: "MRPSNE90A10Z116A",
      },
      {
        id: 2,
        firstName: "Aoife",
        lastName: "Kelly",
        phone: "3524445566",
        email: "aoife.kelly@example.com",
        fiscalCode: "KLLFOA96B41Z116B",
      },
      {
        id: 3,
        firstName: "Liam",
        lastName: "O'Brien",
        phone: "3527778899",
        email: "liam.obrien@example.com",
        fiscalCode: "BRNLMI89C10Z116C",
      },
      {
        id: 4,
        firstName: "Ciara",
        lastName: "Walsh",
        phone: "3522223344",
        email: "ciara.walsh@example.com",
        fiscalCode: "WLSCRA95D41Z116D",
      },
      {
        id: 5,
        firstName: "Conor",
        lastName: "Byrne",
        phone: "3525556677",
        email: "conor.byrne@example.com",
        fiscalCode: "BRN CNR91E15Z116E".replace(" ", ""),
      },
      {
        id: 6,
        firstName: "Niamh",
        lastName: "Ryan",
        phone: "3528889900",
        email: "niamh.ryan@example.com",
        fiscalCode: "RYNNMH97F41Z116F",
      },
      {
        id: 7,
        firstName: "Patrick",
        lastName: "Doyle",
        phone: "3523334455",
        email: "patrick.doyle@example.com",
        fiscalCode: "DYLPRC90G10Z116G",
      },
      {
        id: 8,
        firstName: "Erin",
        lastName: "McCarthy",
        phone: "3526667788",
        email: "erin.mccarthy@example.com",
        fiscalCode: "MCCRNE96H41Z116H",
      },
      {
        id: 9,
        firstName: "Cillian",
        lastName: "Fitzgerald",
        phone: "3529990011",
        email: "cillian.fitzgerald@example.com",
        fiscalCode: "FTZCLL88I10Z116I",
      },
      {
        id: 10,
        firstName: "Megan",
        lastName: "Dunne",
        phone: "3521239988",
        email: "megan.dunne@example.com",
        fiscalCode: "DNNMGN96L41Z116J",
      },
      {
        id: 11,
        firstName: "Owen",
        lastName: "Gallagher",
        phone: "3527776655",
        email: "owen.gallagher@example.com",
        fiscalCode: "GLLWNO89M10Z116K",
      },
      {
        id: 12,
        firstName: "Clodagh",
        lastName: "Kennedy",
        phone: "3525554433",
        email: "clodagh.kennedy@example.com",
        fiscalCode: "KNNCLD95N41Z116L",
      },
      {
        id: 13,
        firstName: "Finn",
        lastName: "Quinn",
        phone: "3524443322",
        email: "finn.quinn@example.com",
        fiscalCode: "QNNFNN90P10Z116M",
      },
      {
        id: 14,
        firstName: "Roisin",
        lastName: "Murray",
        phone: "3523332211",
        email: "roisin.murray@example.com",
        fiscalCode: "MRRRSN97R41Z116N",
      },
      {
        id: 15,
        firstName: "Eoin",
        lastName: "Hughes",
        phone: "3522221100",
        email: "eoin.hughes@example.com",
        fiscalCode: "HGHSNE91S10Z116P",
      },
    ],
  },
];

export function TripsProvider({ children }) {
    const [trips, setTrips] = useState(initialTrips);

    function addTrip(newTrip){
      setTrips(prev => [...prev, newTrip])
    }

    const value = {trips, addTrip}

    return (
        <TripsContext.Provider value={value}>
            {children}
        </TripsContext.Provider>
    )
}

export function useTrips() {

    return useContext(TripsContext)

}


